pom.xml, src/main/resources/application.properties
This PR accomplishes the following part of Assignment 3:
> Create a database that will be shared by all teams members in the organization. Follow the instructions discussed in class to create a database on Heroku. Call the database based on the name of the organization: cs4500_sp19_<organization-name>, e.g., cs4500_sp19_tesla, cs4500_sp19_spacex. Make note of the username, password, and URL connection string. Configure pom file to install MySQL libraries. Configure application properties file to connect to the database. Add, commit, and push all configuration to the remote github repository as well as the heroku repository. Later individual tasks will make use of the database setup. Share the database connection URL, username and password with the TAs and instructors as a deliverable. …
=> Create database and connect to project

src/main/java/edu/neu/cs4500/models/ServiceCategory.java, src/main/resources/sql/create_service_categories_table.sql
Added a service category model object as well as a SQL script for creating the model within db.
=> Service category model

src/main/java/edu/neu/cs4500/models/Service.java, src/main/resources/sql/create_services_table.sql
Created Service model using JPA.
=> Service model

src/main/java/edu/neu/cs4500/repositories/UserRepository.java, src/main/resources/sql/insert_users.sql
This pull request adds the user repository per Assignment 3.
=> Add user repository

.gitignore, src/main/java/edu/neu/cs4500/services/UserService.java
Implemented base CRUD functionalities
- findAllUsers
- findUserById
- createUser
- updateUser
- deleteUser
=> Create simple user service class

src/main/java/edu/neu/cs4500/models/User.java
Constructor is leading to the following exception.
```No default constructor for entity: : edu.neu.cs4500.models.User; nested exception is org.hibernate.InstantiationException: No default constructor for entity: : edu.neu.cs4500.models.User```
https://cs4500-sp19-nowayjose.herokuapp.com/api/users
=> Remove constructor from User

src/main/java/edu/neu/cs4500/repositories/ServiceRepository.java, src/main/resources/sql/insert_services.sql
Created services repository and added sql command used to populate services database
=> Service repo

src/main/java/edu/neu/cs4500/models/Service.java, src/main/java/edu/neu/cs4500/models/ServiceQuestion.java, src/main/java/edu/neu/cs4500/models/ServiceQuestionAnswer.java, src/main/java/edu/neu/cs4500/models/User.java, src/main/java/edu/neu/cs4500/repositories/ServiceQuestionAnswerRepository.java, src/main/java/edu/neu/cs4500/repositories/ServiceQuestionRepository.java, src/main/java/edu/neu/cs4500/services/ServiceQuestionAnswerService.java, src/main/resources/sql/create_service_question_answers_table.sql, src/main/resources/sql/create_service_question_tables.sql, src/main/resources/sql/insert_service_question_answers.sql, src/main/resources/sql/insert_service_questions.sql
Adds a service for CRUD operations on service question answers
=> Service question answers service

src/main/java/edu/neu/cs4500/models/ServiceQuestion.java, src/main/java/edu/neu/cs4500/services/ServiceQuestionService.java
Need help on the REST api entities
=> Service question service

src/main/java/edu/neu/cs4500/services/FrequentlyAskedAnswerService.java
Fixed api path and refactored some methods
=> Faq answer service

src/main/java/edu/neu/cs4500/services/ServiceQuestionService.java
Allow CORS for service questions
=> CORS for service questions

src/main/java/edu/neu/cs4500/services/FrequentlyAskedAnswerService.java
=> Added cross origins support for faq answers

src/main/java/edu/neu/cs4500/models/ServiceQuestionAnswer.java, src/main/java/edu/neu/cs4500/services/ServiceQuestionAnswerService.java
Added Cors in the correct file.
=> added cors correctly and added comments for model

src/main/java/edu/neu/cs4500/models/SearchCriteria.java, src/main/java/edu/neu/cs4500/models/ServiceQuestion.java, src/main/java/edu/neu/cs4500/repositories/ServiceSearch.java
Search service providers by some answer criteria
=> Service provider search

pom.xml, src/main/java/edu/neu/cs4500/models/SearchCriteria.java, src/main/java/edu/neu/cs4500/models/Service.java, src/main/java/edu/neu/cs4500/models/ServiceQuestion.java, src/main/java/edu/neu/cs4500/models/ServiceQuestionAnswer.java, src/main/java/edu/neu/cs4500/models/User.java, src/test/java/edu/neu/cs4500/models/SearchCriteriaTest.java, src/test/java/edu/neu/cs4500/services/SearchServiceTest.java
- Added a correct version for Jupiter library.
- Modified Setters in each model to return the Model self after setting
- Modified the boilerplate testing library
- Fixed bugs in search algorithms
=> Added empty case for search criteria

src/main/java/edu/neu/cs4500/models/Estimate.java, src/test/java/edu/neu/cs4500/models/SubscriptionEstimateDiscountTest.java
=> Created test suite and Added flat discount test

src/main/java/edu/neu/cs4500/services/ServiceQuestionService.java
added an endpoint to filter down service questions
=> added an endpoint for filter

src/test/java/edu/neu/cs4500/services/ServiceQuestionServiceTest.java
=> changed the url

src/main/java/edu/neu/cs4500/services/UserService.java
updateUser did not carry over the username field from the database. 1 line of code fix
=> fix bug in updateUser method

src/main/java/edu/neu/cs4500/models/ServiceProvider.java, src/main/java/edu/neu/cs4500/repositories/ServiceProviderRepository.java, src/main/java/edu/neu/cs4500/services/ServiceProviderService.java
1. Fixed dependency issue with the data model
2. add endpoints for adding service providers and search
=> two endpoints for service provider

src/main/java/edu/neu/cs4500/models/Service.java
=> Add image to service

src/main/java/edu/neu/cs4500/models/ServiceProvider.java, src/main/java/edu/neu/cs4500/services/ServiceProviderService.java, src/test/java/edu/neu/cs4500/services/ServiceProviderSearchTest.java
=> added tests for conditional query

src/main/java/edu/neu/cs4500/models/ServiceProvider.java, src/main/java/edu/neu/cs4500/models/User.java, src/main/java/edu/neu/cs4500/services/UserService.java
linked user and service provider and added an endpoint to determine if the user is a service provider
=> model change to user and service provider

src/main/java/edu/neu/cs4500/repositories/FrequentlyAskedAnswerRepository.java, src/main/java/edu/neu/cs4500/services/FrequentlyAskedAnswerService.java, src/main/java/edu/neu/cs4500/services/FrequentlyAskedQuestionService.java, src/main/java/edu/neu/cs4500/services/UserService.java
Deleting a user or faq now deletes any associated faq answers with it
=> Fix faq answers bug

src/main/java/edu/neu/cs4500/services/UserService.java
Reverts cs4500-sp19-nowayjose/cs4500-sp19-nowayjose#105
=> Revert "Update UserService.java"
